---
apiVersion: apps/v1
# Kind Denotes it is calling Deployment API
kind: Deployment
metadata:
  name: ecomm-app
  namespace: ecomm
spec:
  selector:
    matchLabels: 
      app: ecomm
      tier: app
  replicas: 2
  minReadySeconds: 5
  progressDeadlineSeconds: 300
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template: 
    metadata:
      labels:
        app: ecomm
        tier: app
    spec:
      containers:
      - name: ecommapp
        # Image Name
        image: mohanraz81/hpdcpython
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.3"
            memory: "300Mi"
          requests:
            cpu: "0.2"
            memory: "200Mi"