apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: product-proxy
  name: product-api
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: product-api
  type: LoadBalancer
status:
  loadBalancer: {}
