---
apiVersion: apps/v1
# Kind Denotes it is calling Deployment API
kind: Deployment
metadata:
  name: ecomm-db
  namespace: ecomm
spec:
  selector:
    matchLabels: 
      app: ecomm
      tier: db
  replicas: 1
  minReadySeconds: 5
  progressDeadlineSeconds: 300
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template: 
    metadata:
      labels:
        app: ecomm
        tier: db
    spec:
      containers:
      - name: cartdb
        image: mysql
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: "0.3"
            memory: "500Mi"
          requests:
            cpu: "0.2"
            memory: "200Mi"
        env:
          - name: "MYSQL_ROOT_PASSWORD"
            value: "admin123"
          - name: "MYSQL_DATABASE"
            value: "cartdb"
          - name: "MYSQL_USER"
            value: "dbusername"
          - name: "MYSQL_PASSWORD"
            value: "dbpassword"