---
kind: Service
apiVersion: v1
metadata:
  name: api
  namespace: ecomm
spec:
  selector:
    app: ecomm
    tier: app
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
