---
- name: deploy the hpdc lab
  hosts: localhost
  tasks:
  - name: launch a vpc
    cloudformation:
      stack_name: "vpc"
      state: "present"
      region: "us-east-1"
      disable_rollback: true
      template: "vpc.yaml"
    register: vpcout
  - debug:
      var: vpcout
  - name: launch a dynamodb
    cloudformation:
      stack_name: "dynamodb"
      state: "present"
      region: "us-east-1"
      disable_rollback: true
      template: "dynamodb.yaml"
    register: dynamodbout
  - name: example ec2 key
    ec2_key:
      region: "us-east-1"
      name: ecommkey
    register: ecommkeyout
  - debug:
      var: ecommkeyout
  - name: example copying file with owner and permissions
    copy:
      content: "{{ecommkeyout.key.private_key}}"
      dest: ecomm.pem
      mode: 0600
    when: ecommkeyout is changed
  - name: launch a amiinstance
    cloudformation:
      stack_name: "amiinstance"
      state: "present"
      region: "us-east-1"
      disable_rollback: true
      template: "amiinstance.yaml"
      template_parameters:
         VPCID: "{{vpcout.stack_outputs.VPCID}}"
         SubnetId: "{{vpcout.stack_outputs.PublicSubnet1ID}}"
    register: amiinstanceout
  - name: wait for mahine to configure
    command: sleep 120
  - name: Stop ami instance
    amazon.aws.ec2:
      region: "us-east-1"
      instance_ids: 
        - "{{amiinstanceout.stack_outputs.EC2InstanceId}}"
      state: stopped
      wait: yes
  - name: Basic AMI Creation
    amazon.aws.ec2_ami:
      region: "us-east-1"
      instance_id: "{{amiinstanceout.stack_outputs.EC2InstanceId}}"
      wait: yes
      name: ecomm-ami-1.0
      tags:
        Name: ecomm-ami-1.0
      state: present
    register: amiout
    
  - debug:
      var: amiout
  - name: Deploy Autoscaling and ALb
    cloudformation:
      stack_name: "autoscaling"
      state: "present"
      region: "us-east-1"
      disable_rollback: true
      template: "autoscaling.yaml"
      template_parameters:
        VPCID: "{{vpcout.stack_outputs.VPCID}}"
        PublicSubnet1ID: "{{vpcout.stack_outputs.PublicSubnet1ID}}"
        PublicSubnet2ID: "{{vpcout.stack_outputs.PublicSubnet2ID}}"
        PrivateSubnet1ID: "{{vpcout.stack_outputs.PrivateSubnet1ID}}"
        PrivateSubnet2ID: "{{vpcout.stack_outputs.PrivateSubnet2ID}}"
        KeyName: ecommkey
        Ami: "{{amiout.image_id}}"
         

