#!/bin/bash
sudo pip install boto boto3 botocore
sudo yum -y install ansible
ansible-galaxy collection install community.aws
ansible-playbook deployansible.yaml -e ansible_python_interpreter=/usr/bin/python
#aws cloudformation create-stack --stack-name $1 --template-body file://$1.yaml
