apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: product-proxy
  name: product-api
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 80
  selector:
    io.kompose.service: product-api
status:
  loadBalancer: {}
