apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: product-proxy
  name: product-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: product-proxy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: product-proxy
    spec:
      containers:
        - image: productproxy
          name: product-proxy
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
