apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ecomm-fe
  name: ecomm-fe
spec:
  ports:
    - name: "9091"
      port: 9091
      targetPort: 80
  selector:
    io.kompose.service: ecomm-fe
  type: LoadBalancer
status:
  loadBalancer: {}
