---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: product-hpa
  namespace: product
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-api
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20
